apiVersion: batch.tensorstack.dev/v1beta1
kind: PyTorchTrainingJob
metadata:
  name: nanogpt
spec:
  # scheduler:
  #   t9kScheduler:
  #     queue: default
  #     priority: 50
  torchrunConfig:
    enable: true
    maxRestarts: 3
    procPerNode: "8"
    rdzvBackend: c10d
  replicaSpecs:
    - type: node
      replicas: 2
      restartPolicy: ExitCode
      template:
        spec:
          containers:
            - name: pytorch
              args:
                - train.py
                - config/train_gpt2.py
              workingDir: /t9k/mnt/examples/nanogpt/
              image: t9kpublic/nanogpt:test-v1
              env:
                - name: NCCL_IB_HCA  # configure IB network
                  value: 'mlx5'
                - name: NCCL_IB_DISABLE
                  value: '0'
                - name: NCCL_DEBUG
                  value: 'INFO'
                - name: NCCL_DEBUG_SUBSYS
                  value: 'INIT,ENV,NET,TUNING'
              securityContext:
                capabilities:
                  add: [ "IPC_LOCK" ]
              resources:
                requests:
                  cpu: 16
                  memory: 256Gi
                  nvidia.com/gpu: 8
                  rdma/rdma_shared_device_a: 1  # request RDMA networking card
                limits:
                  cpu: 32
                  memory: 512Gi
                  nvidia.com/gpu: 8
                  rdma/rdma_shared_device_a: 1
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
                - mountPath: /dev/shm
                  name: dshm  
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: nanogpt
            - name: dshm
              emptyDir:
                medium: Memory
