apiVersion: v1
kind: Pod
metadata:
  name: mlperf-nlp-download-dataset
spec:
  restartPolicy: Never
  containers:
    - name: worker
      image: registry.tensorstack.cn/t9k/mlperf-nvidia:language_model
      args:
        - sleep
        - "1000000"
      resources:
        limits:
          cpu: 24
          memory: 128Gi
          nvidia.com/gpu: 1
      volumeMounts:
        - mountPath: /pvc
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mlperf
