apiVersion: batch.tensorstack.dev/v1beta1
kind: DeepSpeedJob
metadata:
  name: llama2-rm-single-gpu
spec:
  # runMode:
  #   debug:
  #     enable: true
  #     replicaSpecs:
  #       - type: worker
  #         skipInitContainer: true
  #         command: ["sleep", "inf"]
  scheduler:
    t9kScheduler:
      queue: mlperf
      priority: 50
  config:
    slotsPerWorker: 1
    run:
      python:
        - ./src/train_bash.py
        # - "--deepspeed=/t9k/mnt/ds-config.json"
        - "--stage=rm"
        - "--model_name_or_path=/t9k/mnt/models/Llama-2-7b-hf"
        - "--do_train"
        - "--dataset=comparison_gpt4_zh"
        - "--template=default"
        - "--finetuning_type=lora"
        - "--lora_target=q_proj,v_proj"
        - "--resume_lora_training=False"
        - "--checkpoint_dir=/t9k/mnt/output/sft-ckpts/llama2/7b/"
        - "--output_dir=/t9k/mnt/output/rm-ckpts/llama2/7b/"
        - "--per_device_train_batch_size=4"
        - "--gradient_accumulation_steps=2"
        - "--lr_scheduler_type=cosine"
        - "--logging_steps=10"
        - "--save_steps=3000"
        - "--learning_rate=1e-6"
        - "--num_train_epochs=1.0"
        - "--plot_loss"
        - "--fp16"
  worker:
    replicas: 1
    template:
      spec:
        containers:
          - name: worker
            workingDir: /t9k/mnt/LLaMA-Efficient-Tuning
            image: tsz.io/xyx/llama-efficient-tuning:20230911
            securityContext:
              capabilities:
                add: [ "IPC_LOCK" ]
            resources:
              requests:
                cpu: 2
                memory: 32Gi
                nvidia.com/gpu: 1
              limits:
                cpu: 4
                memory: 64Gi
                nvidia.com/gpu: 1
            volumeMounts:
              - mountPath: /t9k/mnt
                name: data
              - mountPath: /dev/shm
                name: dshm
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: llama
          - name: dshm
            emptyDir:
              medium: Memory
