apiVersion: tensorstack.dev/v1beta1
kind: MLService
metadata:
  name: tensorizer-gptj
spec:
  default: gptj
  releases:
    - name: gptj
      predictor:
        minReplicas: 1
        model:
          runtime: tensorizer-kserve
        containersResources:
        - name: user-container
          resources:
            limits:
              cpu: 2
              memory: 64Gi
              nvidia.com/gpu: 1
        storage:
          pvc:
            name: tensorizer
