apiVersion: batch.tensorstack.dev/v1beta1
kind: PyTorchTrainingJob
metadata:
  name: qwen2-5-7b-full-sft
spec:
  # runMode:
  #   debug:
  #     enabled: true
  replicaSpecs:
    - type: worker
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: worker
              image: registry.cn-hangzhou.aliyuncs.com/t9k/llamafactory:20250318
              workingDir: /workspace
              command: 
                - llamafactory-cli
                - train
                - examples/llama-factory/training/full-sft-config.yaml
              env:
                - name: HF_ENDPOINT
                  value: "https://hf-mirror.com"
              resources:
                requests:
                  cpu: 4
                  memory: 8Gi
                  nvidia.com/gpu: 4
                limits:
                  cpu: 8
                  memory: 16Gi
                  nvidia.com/gpu: 4
              volumeMounts:
                - mountPath: /workspace
                  name: data
                - mountPath: /dev/shm
                  name: dshm
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: llama-factory
            - name: dshm
              emptyDir:
                medium: Memory
