### model
model_name_or_path: models/Meta-Llama-3.1-70B

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: examples/llama-factory/training/ds_z2_config.json
# deepspeed: examples/llama-factory/training/ds_z3_config.json  # for node with NVLink

### dataset
dataset_dir: examples/llama-factory/data
dataset: identity,alpaca_gpt4_en,alpaca_gpt4_zh,lima,wikiqa,nectar_sft,webqa,stem_zh,mathinstruct
template: default
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-1-70b/lora/sft
logging_steps: 100
save_steps: 2000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 1.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 2000
