apiVersion: tensorstack.dev/v1beta1
kind: MLService
metadata:
  name: mixtral-8x7b
spec:
  scheduler:
    t9kScheduler:
      queue: default
  default: mixtral-8x7b
  releases:
    - name: mixtral-8x7b
      predictor:
        minReplicas: 1
        model:
          runtime: vllm-openai-2xtp
          parameters:
            MODEL_PATH: /var/lib/t9k/model
            MODEL_NAME: mixtral-8x7b
          modelUri: pvc://search/Mixtral-8x7B-Instruct-v0.1
        containersResources:
          - name: user-container
            resources:
              limits:
                cpu: 4
                memory: 64Gi
                nvidia.com/gpu: 2
