apiVersion: batch.tensorstack.dev/v1beta1
kind: DeepSpeedJob
metadata:
  name: deploy-job
spec:
  runMode:
    debug:
      enable: true
  worker:
    replicas: 1
    template:
      spec:
        containers:
          - name: worker
            workingDir: /t9k/mnt/
            image: tsz.io/t9k/deepspeed:chat-0.10.0
            env:
            - name: TRANSFORMERS_CACHE
              value: /t9k/mnt/hf-cache/hub
            - name: HF_DATASETS_CACHE
              value: /t9k/mnt/hf-cache/dataset
            securityContext:
              capabilities:
                add: [ "IPC_LOCK" ]
            resources:
              requests:
                cpu: 4
                memory: 64Gi
                nvidia.com/gpu: 1
              limits:
                cpu: 8
                memory: 128Gi
                nvidia.com/gpu: 1
            volumeMounts:
              - mountPath: /t9k/mnt
                name: data
              - mountPath: /dev/shm
                name: dshm
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: chat
          - name: dshm
            emptyDir:
              medium: Memory
