apiVersion: batch.tensorstack.dev/v1beta1
kind: PyTorchTrainingJob
metadata:
  name: cart-pole
spec:
  # scheduler:
  #   t9kScheduler:
  #     queue: default
  #     priority: 50
  replicaSpecs:
    - type: node
      replicas: 1
      restartPolicy: ExitCode
      template:
        spec:
          containers:
            - name: pytorch
              args:
                - python
                - train.py
                - "-a=dqn"
                - play.py
                - "-a=dqn"
              workingDir: /t9k/mnt/examples/rl/sb3/cart-pole
              image: t9kpublic/sb3:main
              resources:
                requests:
                  cpu: 8
                  memory: 2Gi
                limits:
                  cpu: 16
                  memory: 4Gi
              volumeMounts:
                - mountPath: /t9k/mnt
                  name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: sb3
