apiVersion: tensorstack.dev/v1beta1
kind: ImageBuilder
metadata:
  name: sd
spec:
  builder:
    kaniko:
      image: registry.cn-hangzhou.aliyuncs.com/t9k/kaniko-executor:v1.7.0
  dockerConfig:
    secret: docker-config
  tag: registry.cn-hangzhou.aliyuncs.com/xyxxxxx/stable-diffusion:dcu
  workspace:
    pvc:
      name: sd
      dockerfilePath: ./Dockerfile
      contextPath: .
