apiVersion: batch.tensorstack.dev/v1beta1
kind: PyTorchTrainingJob
metadata:
  name: sd
spec:
  replicaSpecs:
  - type: worker
    replicas: 1
    restartPolicy: OnFailure
    template:
      spec:
        containers:
        - name: sd
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_PTRACE"]
          image: registry.cn-hangzhou.aliyuncs.com/xyxxxxx/stable-diffusion:dcu
          workingDir: /workspace
          command: ["python", "draw.py"]
          env:
          - name: HIP_VISIBLE_DEVICES  # 若不设置该环境变量能看到和使用所有 DCU
            value: "0"
          - name: HF_ENDPOINT
            value: "https://hf-mirror.com"
          resources:
            limits:
              cpu: 4
              memory: 32Gi
              hygon.com/dcu: 1
            requests:
              cpu: 4
              memory: 32Gi
              hygon.com/dcu: 1
          volumeMounts:
          - name: dev-kfd
            mountPath: /dev/kfd
          - name: dev-dri
            mountPath: /dev/dri
          - name: data
            mountPath: /workspace
          - name: data
            mountPath: /root/.cache/huggingface
            subPath: .cache/huggingface
          - name: dshm
            mountPath: /dev/shm
        volumes:
        - name: dev-kfd
          hostPath:
            path: /dev/kfd
        - name: dev-dri
          hostPath:
            path: /dev/dri
        - name: data
          persistentVolumeClaim:
            claimName: sd
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "10Gi"
