apiVersion: batch.tensorstack.dev/v1beta1
kind: DeepSpeedJob
metadata:
  name: neox-elastic
spec:
  elastic:
    enable: true
    minReplicas: 1
    maxReplicas: 3
    expectedReplicas: 3
  runPolicy:
    backoffLimit: 10
  config:
    slotsPerWorker: 2
    localRank: true
    run:
      python:
        - "train.py"
        - "configs/t9k/1-3B_checkpoint.yml"
        - "--vocab_file"
        - "/t9k/mnt/data/gpt2-vocab.json"
        - "--merge_file"
        - "/t9k/mnt/data/gpt2-merges.txt"
        - "--data_path"
        - "/t9k/mnt/data/enwik8/enwik8_text_document"
        - "--checkpoint_dir"
        - "/t9k/mnt/checkpoint"
  worker:
    replicas: 1
    restartPolicy: OnFailure
    template:
      spec:
        containers:
          - image: t9kpublic/deepspeed-neox:23.02-0.10.0-230914
            imagePullPolicy: IfNotPresent
            name: worker
            securityContext:
              capabilities:
                add: ["IPC_LOCK"]
            resources:
              limits:
                cpu: "4"
                memory: 16Gi
                nvidia.com/gpu: 2
                rdma/rdma_shared_device_a: 1
              requests:
                cpu: "2"
                memory: 8Gi
            volumeMounts:
              - mountPath: /t9k/mnt
                name: data
              - mountPath: /dev/shm
                name: shm
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: neox
          - name: shm
            emptyDir:
              medium: Memory
