FROM hpcaitech/colossalai:0.3.0

RUN pip3 install --no-cache-dir -i https://pypi.douban.com/simple --upgrade pip && \
    pip3 install --no-cache-dir -i https://pypi.douban.com/simple --default-timeout=100 transformers datasets
