apiVersion: batch.tensorstack.dev/v1beta1
kind: ColossalAIJob
metadata:
  name: colossal-opt
spec:
  # scheduler:
  #   t9kScheduler:
  #     queue: default
  #     priority: 50
  launcher:
    image: t9kpublic/colossalai:0.2.5-opt
    workingDir: /workspace/ColossalAI/examples/language/opt
  worker:
    replicas: 1
    procPerWorker: 4
    command:
      - train_gemini_opt.py
      - "--model_name_or_path=facebook/opt-350m"
      - "--batch_size=16"
      - "--max_train_steps=100"
      - "--mem_cap=0"
    torchArgs: []
    template:
      spec:
        restartPolicy: OnFailure
        containers:
          - image: t9kpublic/colossalai:0.2.5-opt
            name: worker
            resources:
              limits:
                cpu: 16
                memory: 32Gi
                nvidia.com/gpu: 4
            volumeMounts:
              - mountPath: /root/.cache/huggingface
                name: data
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: colossalai
  runPolicy:
    cleanUpWorkers: true
