apiVersion: tensorstack.dev/v1beta1
kind: MLService
metadata:
  name: mistral-7b
spec:
  # scheduler:
  #   t9kScheduler:
  #     queue: default
  default: mistral-7b
  releases:
    - name: mistral-7b
      predictor:
        minReplicas: 1
        model:
          runtime: vllm-openai
          parameters:
            MODEL_PATH: /var/lib/t9k/model
            MODEL_NAME: mistral-7b
          modelUri: pvc://vllm/Mistral-7B-Instruct-v0.1
        containersResources:
        - name: user-container
          resources:
            limits:
              cpu: 4
              memory: 64Gi
              nvidia.com/gpu: 1
