apiVersion: tensorstack.dev/v1beta1
kind: MLService
metadata:
  name: codellama-34b
spec:
  default: codellama-34b
  releases:
    - name: codellama-34b
      predictor:
        minReplicas: 1
        model:
          runtime: vllm-openai
          parameters:
            MODEL_PATH: /var/lib/t9k/model
            MODEL_NAME: codellama-34b
          modelUri: pvc://vllm/CodeLlama-34b-Instruct-hf
