apiVersion: tensorstack.dev/v1beta1
kind: MLServiceRuntime
metadata:
  name: vllm-openai
spec:
  enabled: true
  template:
    spec:
      containers:
      - name: user-container
        image: t9kpublic/vllm-openai:v0.3.2
        args:
          - --model={{.MODEL_PATH}}
          - --served-model-name={{.MODEL_NAME}}
          - --trust-remote-code
        resources:
          limits:
            cpu: 4
            memory: 64Gi
            nvidia.com/gpu: 1
        ports:
        - containerPort: 8000
