apiVersion: v1
kind: Pod
metadata:
  name: mlperf-minigo-download-dataset
spec:
  restartPolicy: Never
  containers:
    - name: worker
      image: t9kpublic/mlperf-nvidia:minigo
      args:
        - sleep
        - "1000000"
      resources:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          cpu: 8
          memory: 32Gi
      volumeMounts:
        - mountPath: /pvc
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mlperf
