apiVersion: batch.tensorstack.dev/v1beta1
kind: ColossalAIJob
metadata:
  name: colossal-diffusion
spec:
  # scheduler:
  #   t9kScheduler:
  #     queue: default
  #     priority: 50
  launcher:
    image: t9kpublic/colossalai:0.2.5-diffusion
    workingDir: /workspace/ColossalAI/examples/images/diffusion
  worker:
    replicas: 1
    procPerWorker: 2
    command:
      - main.py
      - "--logdir=/tmp/"
      - "--train"
      - "--base=configs/Teyvat/train_colossalai_teyvat.yaml"
      - "--ckpt=512-base-ema.ckpt"
    torchArgs: []
    template:
      spec:
        restartPolicy: OnFailure
        containers:
          - image: t9kpublic/colossalai:0.2.5-diffusion
            name: worker
            resources:
              limits:
                cpu: 8
                memory: 64Gi
                nvidia.com/gpu: 2
  runPolicy:
    cleanUpWorkers: true
