apiVersion: batch.tensorstack.dev/v1beta1
kind: PyTorchTrainingJob
metadata:
  name: lanedet
spec:
  torchrunConfig:
    enable: true
    maxRestarts: 3
    procPerNode: "2"
    rdzvBackend: c10d
  replicaSpecs:
    - type: worker
      replicas: 2
      scalingWeight: 1
      restartPolicy: OnFailure
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: pytorch
              image: t9kpublic/lanedet:230927
              imagePullPolicy: Always
              command:
              - python
              args:
              - main.py
              - configs/scnn/resnet18_tusimple.py
              - --work_dirs
              - /lanedet/data/work_dirs
              resources:
                requests:
                  cpu: 4
                  memory: 8Gi
                  nvidia.com/gpu: 2
                limits:
                  cpu: 8
                  memory: 16Gi
                  nvidia.com/gpu: 2
              workingDir: /lanedet
              volumeMounts:
                - mountPath: /lanedet/data
                  name: data
                - mountPath: /dev/shm
                  name: cache-volume
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: lane
            - emptyDir:
                medium: Memory
              name: cache-volume
