apiVersion: batch.tensorstack.dev/v1beta1
kind: GenericJob
metadata:
  name: llama3-finetune-2x2xdp
spec:
  successRules:
    - { "worker": [0] }
  failureRules:
    - { "worker": [0] }
    - { "worker": [1] }
  replicaSpecs:
    - type: worker
      replicas: 2
      template:
        spec:
          containers:
            - name: llama3
              image: registry.cn-hangzhou.aliyuncs.com/xyxxxxx/pytorch:dcu-2.1.0-xtuner
              workingDir: /workspace/llama3_pytorch
              commands: ["xtuner"]
              args:
                - "train"
                - "llama3_8b_instruct_qlora_alpaca_e3_M.py"
                - "--deepspeed=deepspeed_zero2"
              env:
                - name: NPROC_PER_NODE
                  value: "2"
                - name: HIP_VISIBLE_DEVICES  # 若不设置该环境变量能看到和使用所有 DCU
                  value: "0,1"
                - name: NCCL_SOCKET_IFNAME
                  value: "eno1"
              resources:
                limits:
                  cpu: 4
                  memory: 64Gi
                  hygon.com/dcu: 2
                requests:
                  cpu: 4
                  memory: 64Gi
                  hygon.com/dcu: 2
              volumeMounts:
                - name: hyhal
                  mountPath: /opt/hyhal
                  readOnly: true
                - name: dev-kfd
                  mountPath: /dev/kfd
                  readOnly: true
                - name: dev-dri
                  mountPath: /dev/dri
                  readOnly: true
                - name: workingdir
                  mountPath: /t9k/mnt
                - name: dshm
                  mountPath: /dev/shm
          volumes:
            - name: hyhal
              hostPath:
                path: /opt/hyhal
            - name: dev-kfd
              hostPath:
                path: /dev/kfd
            - name: dev-dri
              hostPath:
                path: /dev/dri
            - name: workingdir
              persistentVolumeClaim:
                claimName: llama3
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: "80Gi"
