apiVersion: batch.tensorstack.dev/v1beta1
kind: DeepSpeedJob
metadata:
  name: actor-single-node
spec:
  config:
    slotsPerWorker: 2
    run:
      python: [
        "./chat/actor/main.py",
        "--data_path", "./datasets/Dahoas/rm-static", "./datasets/Dahoas/full-hh-rlhf", "./datasets/Dahoas/synthetic-instruct-gptj-pairwise", "./datasets/yitingxie/rlhf-reward-datasets",
        "--data_split", "2,4,4",
        "--model_name_or_path", "/t9k/mnt/models/llama-7b",
        "--per_device_train_batch_size", "8",
        "--per_device_eval_batch_size", "8",
        "--max_seq_len", "512",
        "--learning_rate", "1e-4",
        "--weight_decay", "0.1",
        "--num_train_epochs", "2",
        "--gradient_accumulation_steps", "1",
        "--lr_scheduler_type", "cosine",
        "--num_warmup_steps", "0",
        "--seed", "1234",
        "--gradient_checkpointing",
        "--zero_stage", "0",
        "--lora_dim", "128",
        "--lora_module_name", "decoder.layers.",
        "--deepspeed",
        "--output_dir", "./output/single-node/actor-models/7b"
      ]
  worker:
    replicas: 1
    template:
      spec:
        containers:
          - name: worker
            workingDir: /t9k/mnt/
            image: tsz.io/lmh/deepspeed-0.9.1-chat:0.0.1
            securityContext:
              capabilities:
                add: [ "IPC_LOCK" ]
            resources:
              requests:
                cpu: 4
                memory: 64Gi
                nvidia.com/gpu: 2
              limits:
                cpu: 8
                memory: 128Gi
                nvidia.com/gpu: 2
            volumeMounts:
              - mountPath: /t9k/mnt/models/llama-7b
                name: model
              - mountPath: /t9k/mnt
                name: code
              - mountPath: /dev/shm
                name: dshm
        volumes:
          - name: code
            persistentVolumeClaim:
              claimName: gpt
          - name: model
            persistentVolumeClaim:
              claimName: llama-7b
          - name: dshm
            emptyDir:
              medium: Memory
