apiVersion: batch.tensorstack.dev/v1beta1
kind: DeepSpeedJob
metadata:
  name: actor-single-node
spec:
  # scheduler:
  #   t9kScheduler:
  #     queue: default
  #     priority: 50
  config:
    slotsPerWorker: 4
    run:
      python: [
        "./examples/deepspeed/chat/actor/main.py",
        "--data_path", "./datasets/Dahoas/rm-static", "./datasets/Dahoas/full-hh-rlhf", "./datasets/Dahoas/synthetic-instruct-gptj-pairwise",
        "--data_split", "2,4,4",
        "--model_name_or_path", "./models/opt-13b",
        "--per_device_train_batch_size", "8",
        "--per_device_eval_batch_size", "8",
        "--max_seq_len", "512",
        "--learning_rate", "1e-4",
        "--weight_decay", "0.1",
        "--num_train_epochs", "2",
        "--gradient_accumulation_steps", "1",
        "--lr_scheduler_type", "cosine",
        "--num_warmup_steps", "0",
        "--seed", "1234",
        "--gradient_checkpointing",
        "--zero_stage", "2",
        "--lora_dim", "128",
        "--lora_module_name", "decoder.layers.",
        "--deepspeed",
        "--output_dir", "./output/single-node/actor-models/13b"
      ]
  worker:
    replicas: 1
    template:
      spec:
        containers:
          - name: worker
            workingDir: /t9k/mnt/
            image: t9kpublic/deepspeed:chat-0.9.0
            securityContext:
              capabilities:
                add: [ "IPC_LOCK" ]
            resources:
              requests:
                cpu: 8
                memory: 128Gi
                nvidia.com/gpu: 4
              limits:
                cpu: 16
                memory: 256Gi
                nvidia.com/gpu: 4
            volumeMounts:
              - mountPath: /t9k/mnt
                name: data
              - mountPath: /dev/shm
                name: dshm
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: dschat
          - name: dshm
            emptyDir:
              medium: Memory
