apiVersion: batch.tensorstack.dev/v1beta1
kind: ColossalAIJob
metadata:
  name: colossal-palm
spec:
  # scheduler:
  #   t9kScheduler:
  #     queue: default
  #     priority: 50
  launcher:
    image: t9kpublic/colossalai:0.2.5-palm
    workingDir: /workspace/ColossalAI/examples/language/palm
  worker:
    replicas: 1
    procPerWorker: 4
    command:
      - train.py
      - "--distplan=colossalai"
      - "--batch_num=100"
      # - "--dummy_data=True"
    torchArgs: []
    template:
      spec:
        restartPolicy: OnFailure
        containers:
          - image: t9kpublic/colossalai:0.2.5-palm
            name: worker
            resources:
              limits:
                cpu: 16
                memory: 32Gi
                nvidia.com/gpu: 4
  runPolicy:
    cleanUpWorkers: true
