apiVersion: batch.tensorstack.dev/v1beta1
kind: DeepSpeedJob
metadata:
  name: rlhf-single-gpu
spec:
  config:
    run:
      python: [
        "examples/deepspeed/chat/rlhf/main.py",
        "--data_path", "datasets/Dahoas/rm-static", "datasets/Dahoas/full-hh-rlhf", "datasets/Dahoas/synthetic-instruct-gptj-pairwise",
        "--data_split", "2,4,4",
        "--tokenizer_name_or_path", "models/opt-1.3b",
        "--actor_model_name_or_path", "output/single-gpu/actor-models/1.3b",
        "--critic_model_name_or_path", "output/single-gpu/reward-models/350m",
        "--num_padding_at_beginning", "1",
        "--per_device_train_batch_size", "4",
        "--per_device_mini_train_batch_size", "4",
        "--generation_batch_numbers", "1",
        "--ppo_epochs", "1",
        "--max_answer_seq_len", "256",
        "--max_prompt_seq_len", "256",
        "--actor_learning_rate", "5e-4",
        "--critic_learning_rate", "5e-6",
        "--actor_weight_decay", "0.1",
        "--critic_weight_decay", "0.1",
        "--num_train_epochs", "1",
        "--lr_scheduler_type", "cosine",
        "--gradient_accumulation_steps", "1",
        "--num_warmup_steps", "100",
        "--deepspeed",
        "--seed", "1234",
        # "--enable_hybrid_engine",  # https://github.com/microsoft/DeepSpeedExamples/issues/587
        "--inference_tp_size", "1",
        "--actor_zero_stage", "3",
        "--critic_zero_stage", "3",
        "--offload_reference_model",
        "--actor_gradient_checkpointing",
        "--critic_gradient_checkpointing",
        "--actor_lora_dim", "128",
        "--actor_lora_module_name", "decoder.layers.",
        "--output_dir", "output/single-gpu/step3-models/1.3b",
      ]
  worker:
    replicas: 1
    template:
      spec:
        containers:
          - name: worker
            workingDir: /t9k/mnt/
            image: tsz.io/t9k/deepspeed:chat-0.10.0
            securityContext:
              capabilities:
                add: [ "IPC_LOCK" ]
            resources:
              requests:
                cpu: 2
                memory: 64Gi
                nvidia.com/gpu: 1
              limits:
                cpu: 4
                memory: 128Gi
                nvidia.com/gpu: 1
            volumeMounts:
              - mountPath: /t9k/mnt
                name: data
              - mountPath: /dev/shm
                name: dshm
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: chat
          - name: dshm
            emptyDir:
              medium: Memory
