apiVersion: batch.tensorstack.dev/v1beta1
kind: DeepSpeedJob
metadata:
  name: rlhf-single-node
spec:
  config:
    slotsPerWorker: 4
    otherArgs: ["--master_port", "12346"]
    run:
      python: [
        "./chat/rlhf/main.py",
        "--data_path", "./datasets/Dahoas/rm-static", "./datasets/Dahoas/full-hh-rlhf", "./datasets/Dahoas/synthetic-instruct-gptj-pairwise",
        "--data_split", "2,4,4",
        "--tokenizer_name_or_path", "./models/opt-13b",
        "--actor_model_name_or_path", "./output/single-node/actor-models/13b",
        "--critic_model_name_or_path", "./output/single-gpu/reward-models/350m",
        "--num_padding_at_beginning", "1",
        "--per_device_train_batch_size", "4",
        "--per_device_mini_train_batch_size", "4",
        "--generation_batch_numbers", "1",
        "--ppo_epochs", "1",
        "--max_answer_seq_len", "256",
        "--max_prompt_seq_len", "256",
        "--actor_learning_rate", "5e-4",
        "--critic_learning_rate", "5e-6",
        "--actor_weight_decay", "0.1",
        "--critic_weight_decay", "0.1",
        "--num_train_epochs", "1",
        "--lr_scheduler_type", "cosine",
        "--gradient_accumulation_steps", "1",
        "--num_warmup_steps", "100",
        "--deepspeed",
        "--seed", "1234",
        # "--enable_hybrid_engine",
        "--inference_tp_size", "1",
        "--actor_zero_stage", "3",
        "--critic_zero_stage", "3",
        "--offload_reference_model",
        "--actor_gradient_checkpointing",
        "--critic_gradient_checkpointing",
        "--actor_lora_dim", "128",
        "--actor_lora_module_name", "decoder.layers.",
        "--output_dir", "./output/single-node/step3-models/13b",
      ]
  worker:
    replicas: 1
    template:
      spec:
        containers:
          - name: worker
            workingDir: /t9k/mnt/
            image: tsz.io/t9k/deepspeed:chat-0.10.0
            securityContext:
              capabilities:
                add: [ "IPC_LOCK" ]
            resources:
              requests:
                cpu: 8
                memory: 256Gi
                nvidia.com/gpu: 4
              limits:
                cpu: 16
                memory: 512Gi
                nvidia.com/gpu: 4
            volumeMounts:
              - mountPath: /t9k/mnt
                name: code
              - mountPath: /dev/shm
                name: dshm
        volumes:
          - name: code
            persistentVolumeClaim:
              claimName: gpt
          - name: dshm
            emptyDir:
              medium: Memory
