apiVersion: v1
kind: Pod
metadata:
  name: mlperf-image-classification-download-dataset
spec:
  restartPolicy: Never
  containers:
    - name: worker
      image: t9kpublic/mlperf-image-classification:v2.1
      args:
        - sleep
        - "1000000"
      resources:
        limits:
          cpu: 2
          memory: 8Gi
      volumeMounts:
        - mountPath: /pvc
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mlperf
