apiVersion: tensorstack.dev/v1beta1
kind: MLServiceRuntime
metadata:
  name: triton-python
spec:
  enabled: true
  template:
    spec:
      containers:
      - name: user-container
        image: t9kpublic/triton-python:20230605
        resources:
          limits:
            cpu: 1
            memory: 16Gi
            nvidia.com/gpu: 1
        ports:
          - containerPort: 8000
