apiVersion: tensorstack.dev/v1beta1
kind: MLServiceRuntime
metadata:
  name: search-with-lepton
spec:
  enabled: true
  template:
    spec:
      containers:
      - name: user-container
        image: t9kpublic/search-with-lepton:20240208
        ports:
        - containerPort: 8080
