apiVersion: batch.tensorstack.dev/v1beta1
kind: DeepSpeedJob
metadata:
  name: reward-single-node
spec:
  config:
    slotsPerWorker: 2
    run:
      python: [
        "/t9k/mnt/chat/reward/main.py",
        "--data_path", "Dahoas/rm-static", "Dahoas/full-hh-rlhf", "Dahoas/synthetic-instruct-gptj-pairwise", "yitingxie/rlhf-reward-datasets",
        "--data_split", "2,4,4",
        "--model_name_or_path", "facebook/opt-350m",
        "--num_padding_at_beginning", "1",
        "--per_device_train_batch_size", "8",
        "--per_device_eval_batch_size", "8",
        "--max_seq_len", "512",
        "--learning_rate", "5e-5",
        "--weight_decay", "0.1",
        "--num_train_epochs", "1",
        "--gradient_accumulation_steps", "1",
        "--lr_scheduler_type", "cosine",
        "--num_warmup_steps", "0",
        "--seed", "1234",
        "--zero_stage", "0",
        "--deepspeed",
        "--output_dir=/t9k/mnt/output/single-node/reward-models/350m"
      ]
  worker:
    replicas: 1
    template:
      spec:
        containers:
          - name: worker
            workingDir: /t9k/mnt/
            image: tsz.io/lmh/deepspeed-0.9.1-chat:0.0.1
            env:
            - name: TRANSFORMERS_CACHE
              value: /t9k/mnt/hf-cache/hub
            - name: HF_DATASETS_CACHE
              value: /t9k/mnt/hf-cache/dataset
            securityContext:
              capabilities:
                add: [ "IPC_LOCK" ]
            resources:
              requests:
                cpu: 4
                memory: 64Gi
                nvidia.com/gpu: 2
              limits:
                cpu: 8
                memory: 128Gi
                nvidia.com/gpu: 2
            volumeMounts:
              - mountPath: /t9k/mnt
                name: data
              - mountPath: /dev/shm
                name: dshm
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: gpt
          - name: dshm
            emptyDir:
              medium: Memory
