### model
model_name_or_path: saves/qwen2-5-7b/full/sft
trust_remote_code: true

### method
finetuning_type: full

### dataset
task: mmlu_test  # choices: [mmlu_test, ceval_validation, cmmlu_test]
task_dir: LLaMA-Factory/evaluation
template: fewshot
lang: en
n_shot: 5

### output
save_dir: saves/qwen2-5-7b/full/eval/sft

### eval
batch_size: 4
