### model
model_name_or_path: models/Qwen2.5-7B-Instruct
adapter_name_or_path: saves/qwen2-5-7b/lora/dpo
trust_remote_code: true

### method
finetuning_type: lora

### dataset
task: mmlu_test  # choices: [mmlu_test, ceval_validation, cmmlu_test]
task_dir: LLaMA-Factory/evaluation
template: fewshot
lang: en
n_shot: 5

### output
save_dir: saves/qwen2-5-7b/lora/eval/dpo

### eval
batch_size: 4
