apiVersion: v1
kind: Pod
metadata:
  name: mlperf-detector-download-dataset
spec:
  restartPolicy: Never
  containers:
    - name: worker
      image: t9kpublic/mlperf-nvidia:single_stage_detector
      args:
        - sleep
        - "1000000"
      resources:
        limits:
          cpu: 2
          memory: 32Gi
      volumeMounts:
        - mountPath: /pvc
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mlperf
